version: '3.3'

#x-environment: &commonEnvironment
#    SETTINGS_CONFIGURATION: 'development'
#    DATABASE_URL: "postgres://fastapi_celery:fastapi_celery@db/fastapi_celery"
#    CELERY_BROKER_URL: "amqp://rabbitmq:5672"
#    CELERY_RESULT_BACKEND: "redis://redis:6379"
#    CELERY_FLOWER_USER: admin
#    CELERY_FLOWER_PASSWORD: admin
#    RABBITMQ_DEFAULT_USER: admin
#    RABBITMQ_DEFAULT_PASS: admin

services:
  nginx:
    build: ./compose/production/nginx
    container_name: nginx-prod
    volumes:
      - uploadfiles:/app/upload
    ports:
      - "8000:80"
      - "5559:5555"
      - "15672:15672"
    depends_on:
      - web
      - flower

  web:
    build:
      context: .
      dockerfile: ./compose/production/fastapi/Dockerfile
    image: fastapi_celery_example_web
    container_name: fastapi-prod
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
       - uploadfiles:/app/upload
    environment:
      - SETTINGS_CONFIGURATION=development
      - DATABASE_URL=postgres://fastapi_celery:fastapi_celery@db/fastapi_celery
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - CELERY_FLOWER_USER=admin
      - CELERY_FLOWER_PASSWORD=admin
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    depends_on:
      - rabbitmq
      - redis
      - db

  db:
    image: postgres:13.4-alpine
    container_name: postgres-prod
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=fastapi_celery
      - POSTGRES_USER=fastapi_celery
      - POSTGRES_PASSWORD=fastapi_celery


  redis:
    image: redis:6.2.5-alpine
    container_name: redis-prod

  rabbitmq:
    image: rabbitmq:3.9.4-management
    container_name: rabbitmq-prod

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/production/fastapi/Dockerfile
    image: fastapi_celery_example_celery_worker
    container_name: worker-prod
    command: /start-celeryworker
    volumes:
       - uploadfiles:/app/upload
    environment:
      - SETTINGS_CONFIGURATION=development
      - DATABASE_URL=postgres://fastapi_celery:fastapi_celery@db/fastapi_celery
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - CELERY_FLOWER_USER=admin
      - CELERY_FLOWER_PASSWORD=admin
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    depends_on:
      - rabbitmq
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/production/fastapi/Dockerfile
    container_name: scheduler-prod
    image: fastapi_celery_example_celery_beat
    command: /start-celerybeat
    volumes:
       - uploadfiles:/app/upload
    environment:
      - SETTINGS_CONFIGURATION=development
      - DATABASE_URL=postgres://fastapi_celery:fastapi_celery@db/fastapi_celery
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - CELERY_FLOWER_USER=admin
      - CELERY_FLOWER_PASSWORD=admin
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    depends_on:
      - rabbitmq
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/production/fastapi/Dockerfile
    image: fastapi_celery_example_celey_flower
    container_name: flower-prod
    command: /start-flower
    volumes:
       - uploadfiles:/app/upload
    environment:
      - SETTINGS_CONFIGURATION=development
      - DATABASE_URL=postgres://fastapi_celery:fastapi_celery@db/fastapi_celery
      - CELERY_BROKER_URL=amqp://rabbitmq:5672
      - CELERY_RESULT_BACKEND=redis://redis:6379
      - CELERY_FLOWER_USER=admin
      - CELERY_FLOWER_PASSWORD=admin
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    depends_on:
      - rabbitmq
      - redis
      - db

volumes:
  postgres_data:
  uploadfiles: