version: '3.8'

x-environment: &commonEnvironment
    SETTINGS_CONFIGURATION: 'development'
    DATABASE_URL: "postgres://fastapi_celery:fastapi_celery@db/fastapi_celery"
    CELERY_BROKER_URL: "amqp://rabbitmq:5672"
    CELERY_RESULT_BACKEND: "redis://redis:6379"

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fastapi_celery_example_web
    container_name: fastapi
    # '/start' is the shell script used to run the service
    command: /start
    # this volume is used to map the files and folders on the host to the container
    # so if we change code on the host, code in the docker container will also be changed
    volumes:
      - .:/opt/ranger
    ports:
      - "8000:8000"
    environment: *commonEnvironment
    depends_on:
      - rabbitmq
      - redis
      - db

  db:
    image: postgres:13.4-alpine
    container_name: postgres
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=fastapi_celery
      - POSTGRES_USER=fastapi_celery
      - POSTGRES_PASSWORD=fastapi_celery
#
#  pgadmin:
#    container_name: pgadmin4
#    image: dpage/pgadmin4
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@admin.com
#      PGADMIN_DEFAULT_PASSWORD: admin
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    ports:
#      - "5050:80"
#    volumes:
#      - pgadmin:/var/lib/pgadmin

  redis:
    image: redis:6.2.5-alpine
    container_name: redis

  rabbitmq:
    image: rabbitmq:3.9.4-management
    container_name: rabbitmq
    ports:
      - "15672:15672"

  celery_worker:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fastapi_celery_example_celery_worker
    container_name: worker
    command: /start-celeryworker
    volumes:
      - .:/opt/ranger
    environment: *commonEnvironment
    depends_on:
      - rabbitmq
      - redis
      - db

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    container_name: scheduler
    image: fastapi_celery_example_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/opt/ranger
    environment: *commonEnvironment
    depends_on:
      - rabbitmq
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fastapi_celery_example_celey_flower
    container_name: flower
    command: /start-flower
    volumes:
      - .:/opt/ranger
    environment: *commonEnvironment
    ports:
      - "5555:5555"
    depends_on:
      - rabbitmq
      - redis
      - db

volumes:
#  postgres_data:
  pgadmin: